import { PrismaClient } from "@prisma/client";


const prisma = new PrismaClient()
async function main() {

    await prisma.branch.createMany({
        data: [
            { branchName: 'Gobi', branchCode: '1GOB' },
            { branchName: 'Mulanur', branchCode: '2MLR' },
            { branchName: 'Pollachi', branchCode: '3POL' },
            { branchName: 'Coimbatore', branchCode: '4CBE' },
            { branchName: 'Tirupur', branchCode: '5TPE' },
            { branchName: 'Erode', branchCode: '6ERD' },
            { branchName: 'Dindigul', branchCode: '7DGL' },
            { branchName: 'Karur', branchCode: '8KRR' }
        ]
    })

    await prisma.district.createMany({
        data: [
            { districtName: "Ariyalur" },
            { districtName: "Chengalpattu" },
            { districtName: "Chennai" },
            { districtName: "Coimbatore" },
            { districtName: "Cuddalore" },
            { districtName: "Dharmapuri" },
            { districtName: "Dindigul" },
            { districtName: "Erode" },
            { districtName: "Kallakurichi" },
            { districtName: "Kancheepuram" },
            { districtName: "Kanniyakumari" },
            { districtName: "Karur" },
            { districtName: "Krishnagiri" },
            { districtName: "Madurai" },
            { districtName: "Mayiladuthurai" },
            { districtName: "Nagapattinam" },
            { districtName: "Namakkal" },
            { districtName: "Nilgris" },
            { districtName: "Perambalur" },
            { districtName: "Pudukottai" },
            { districtName: "Ramanathapuram" },
            { districtName: "Ranipet" },
            { districtName: "Salem" },
            { districtName: "Sivagangai" },
            { districtName: "Tenkasi" },
            { districtName: "Thanjavur" },
            { districtName: "Theni" },
            { districtName: "Thiruvallur" },
            { districtName: "Thiruvannamalai" },
            { districtName: "Thiruvarur" },
            { districtName: "Thoothukudi" },
            { districtName: "Tiruchirappalli" },
            { districtName: "Tirunelveli" },
            { districtName: "Tirupathur" },
            { districtName: "Tirupur" },
            { districtName: "Vellore" },
            { districtName: "Villupuram" },
            { districtName: "Virudhunagar" },
        ]
    })

    await prisma.user.create({
        data: {
            fullName: 'Direct', phoneNumber: '', password: '', email: ''
        }
    })



    const taluks = [
        ["Alandur", "Chennai", null],
        ["Ambattur", "Chennai", null],
        ["Aminjikarai", "Chennai", null],
        ["Ayanavaram", "Chennai", null],
        ["Egmore", "Chennai", null],
        ["Guindy", "Chennai", null],
        ["Madhavaram", "Chennai", null],
        ["Madhuravoyal", "Chennai", null],
        ["Mambalam", "Chennai", null],
        ["Mylapore", "Chennai", null],
        ["Perambur", "Chennai", null],
        ["Purasavakkam", "Chennai", null],
        ["Sholinganallur", "Chennai", null],
        ["Thiruvottriyur", "Chennai", null],
        ["Tondiarpet", "Chennai", null],
        ["Velacherry", "Chennai", null],
        ["Aanaimalai", "Coimbatore", "3POL"],
        ["Annur", "Coimbatore"],
        ["Kinathukadavu", "Coimbatore", "3POL"],
        ["Madukarai", "Coimbatore", "4CBE"],
        ["Mettupalayam", "Coimbatore", "4CBE"],
        ["Perur", "Coimbatore", "4CBE"],
        ["Pollachi", "Coimbatore", "3POL"],
        ["Sulur", "Coimbatore", "4CBE"],
        ["Valparai", "Coimbatore", "3POL"],
        ["Cuddalore", "Cuddalore", null],
        ["Bhuvanagiri", "Cuddalore", null],
        ["Chidambaram", "Cuddalore", null],
        ["Kattumannarkoil", "Cuddalore", null],
        ["Kurinjipadi", "Cuddalore", null],
        ["Panruti", "Cuddalore", null],
        ["Srimushnam", "Cuddalore", null],
        ["Thittakudi", "Cuddalore", null],
        ["Veppur", "Cuddalore", null],
        ["Virudhachalam", "Cuddalore", null],
        ["Dharmapuri", "Dharmapuri", null],
        ["Harur", "Dharmapuri", null],
        ["Karimangalam", "Dharmapuri", null],
        ["Nallampalli", "Dharmapuri", null],
        ["Palacode", "Dharmapuri", null],
        ["Pappireddipatti", "Dharmapuri", null],
        ["Pennagaram", "Dharmapuri", null],
        ["Atthur", "Dindigul", "7DGL"],
        ["Dindigul (East)", "Dindigul", "7DGL"],
        ["Dindigul (West)", "Dindigul", "7DGL"],
        ["Guziliyamparai", "Dindigul", "8KRR"],
        ["Kodaikanal", "Dindigul", "7DGL"],
        ["Natham", "Dindigul", "7DGL"],
        ["Nilakottai", "Dindigul", "7DGL"],
        ["Oddanchatram", "Dindigul", "2MLR"],
        ["Palani", "Dindigul", "2MLR"],
        ["Vedasandur", "Dindigul", "7DGL"],
        ["Erode", "Erode", "6ERD"],
        ["Anthiyur", "Erode", "1GOB"],
        ["Bhavani", "Erode", "6ERD"],
        ["Gobichettipalayam", "Erode", "1GOB"],
        ["Kodumudi", "Erode", "6ERD"],
        ["Modakurichi", "Erode", "6ERD"],
        ["Nambiyur", "Erode", "1GOB"],
        ["Perundurai", "Erode", "1GOB"],
        ["Sathiyamangalam", "Erode", "1GOB"],
        ["Thalavadi", "Erode", "1GOB"],
        ["Kancheepuram", "Kancheepuram", null],
        ["Kundrathur", "Kancheepuram", null],
        ["Sriperumbudur", "Kancheepuram", null],
        ["Uthiramerur", "Kancheepuram", null],
        ["Walajabad", "Kancheepuram", null],
        ["Agasteeswaram", "Kanniyakumari", null],
        ["Kalkulam", "Kanniyakumari", null],
        ["Killiyur", "Kanniyakumari", null],
        ["Thiruvatar", "Kanniyakumari", null],
        ["Thovalai", "Kanniyakumari", null],
        ["Vilavankodu", "Kanniyakumari", null],
        ["Karur", "Karur", "8KRR"],
        ["Aravakurichi", "Karur", "2MLR"],
        ["Kadavur", "Karur", "8KRR"],
        ["Krishnarayapuram", "Karur", "8KRR"],
        ["Kulithalai", "Karur", "8KRR"],
        ["Manmangalam", "Karur", "8KRR"],
        ["Pugalur", "Karur", null],
        ["Kallikudi", "Madurai", null],
        ["Madurai (East)", "Madurai", null],
        ["Madurai (North)", "Madurai", null],
        ["Madurai (South)", "Madurai", null],
        ["Madurai (West)", "Madurai", null],
        ["Melur", "Madurai", null],
        ["Peraiyur", "Madurai", null],
        ["Thirumangalam", "Madurai", null],
        ["Thiruparankundram", "Madurai", null],
        ["Usilampatti", "Madurai", null],
        ["Vadipatti", "Madurai", "7DGL"],
        ["Nagapattinam", "Nagapattinam", null],
        ["Kilvelur", "Nagapattinam", null],
        ["Thirukkuvalai", "Nagapattinam", null],
        ["Vedaranyam", "Nagapattinam", null],
        ["Namakkal", "Namakkal", "8KRR"],
        ["Kholli Hills", "Namakkal", null],
        ["Kumarapalayam", "Namakkal", "6ERD"],
        ["Mohanoor", "Namakkal", "8KRR"],
        ["Paramathi Velur", "Namakkal", "8KRR"],
        ["Rasipuram", "Namakkal", "6ERD"],
        ["Senthamangalam", "Namakkal", null],
        ["Tiruchengode", "Namakkal", "6ERD"],
        ["Udagamandalam", "Nilgris", null],
        ["Coonoor", "Nilgris", null],
        ["Gudalur", "Nilgris", null],
        ["Kothagiri", "Nilgris", null],
        ["Kundah", "Nilgris", null],
        ["Pandalur", "Nilgris", null],
        ["Perambalur", "Perambalur", null],
        ["Alathur", "Perambalur", null],
        ["Kunnam", "Perambalur", null],
        ["Veppanthattai", "Perambalur", null],
        ["Pudukottai", "Pudukottai", null],
        ["Alangudi", "Pudukottai", null],
        ["Aranthangi", "Pudukottai", null],
        ["Avudiyarkoil", "Pudukottai", null],
        ["Gandarvakottai", "Pudukottai", null],
        ["Iluppur", "Pudukottai", null],
        ["Karambakudi", "Pudukottai", null],
        ["Kulathur", "Pudukottai", null],
        ["Manamelkudi", "Pudukottai", null],
        ["Ponnamaravathi", "Pudukottai", null],
        ["Thirumayam", "Pudukottai", null],
        ["Viralimalai", "Pudukottai", null],
        ["Ramanathapuram", "Ramanathapuram", null],
        ["Kadaladi", "Ramanathapuram", null],
        ["Kamuthi", "Ramanathapuram", null],
        ["Kezhakarai", "Ramanathapuram", null],
        ["Mudukulathur", "Ramanathapuram", null],
        ["Paramakudi", "Ramanathapuram", null],
        ["Rajasingamangalam", "Ramanathapuram", null],
        ["Rameswaram", "Ramanathapuram", null],
        ["Tiruvadanai", "Ramanathapuram", null],
        ["Salem", "Salem", "6ERD"],
        ["Attur", "Salem", "7DGL"],
        ["Edapadi", "Salem", "6ERD"],
        ["Gangavalli", "Salem", null],
        ["Kadaiyampatti", "Salem", null],
        ["Mettur", "Salem", "1GOB"],
        ["Omalur", "Salem", "6ERD"],
        ["Pethanayakanpalayam", "Salem", null],
        ["Salem South", "Salem", "6ERD"],
        ["Salem West", "Salem", "6ERD"],
        ["Sankari", "Salem", null],
        ["Vazhapadi", "Salem", null],
        ["Yercaud", "Salem", null],
        ["Sivagangai", "Sivagangai", null],
        ["Devakottai", "Sivagangai", null],
        ["Ilayankudi", "Sivagangai", null],
        ["Kalaiyarkovil", "Sivagangai", null],
        ["Karaikudi", "Sivagangai", null],
        ["Manamadurai", "Sivagangai", null],
        ["Singampunari", "Sivagangai", null],
        ["Thirupuvanam", "Sivagangai", null],
        ["Thanjavur", "Thanjavur", null],
        ["Boothalur", "Thanjavur", null],
        ["Kumbakonam", "Thanjavur", null],
        ["Orathanadu", "Thanjavur", null],
        ["Papanasam", "Thanjavur", null],
        ["Pattukottai", "Thanjavur", null],
        ["Peravurani", "Thanjavur", null],
        ["Thiruvaiyaru", "Thanjavur", null],
        ["Thiruvidaimaruthur", "Thanjavur", null],
        ["Theni", "Theni", null],
        ["Aandipatti", "Theni", null],
        ["Bodinayakanur", "Theni", null],
        ["Periyakulam", "Theni", "7DGL"],
        ["Uthamapalayam", "Theni", null],
        ["Thiruvallur", "Thiruvallur", null],
        ["Avadi", "Thiruvallur", null],
        ["Gummidipoondi", "Thiruvallur", null],
        ["Pallipattu", "Thiruvallur", null],
        ["Ponneri", "Thiruvallur", null],
        ["Poonamallee"], "Thiruvallur", null,
        ["R.K. Pet", "Thiruvallur", null],
        ["Tiruthani", "Thiruvallur", null],
        ["Uthukottai", "Thiruvallur", null],
        ["Thiruvannamalai", "Thiruvannamalai", null],
        ["Arni", "Thiruvannamalai", null],
        ["Chengam", "Thiruvannamalai", null],
        ["Chetpet", "Thiruvannamalai", null],
        ["Cheyyar", "Thiruvannamalai", null],
        ["Jamunamarathur", "Thiruvannamalai", null],
        ["Kalasapakkam", "Thiruvannamalai", null],
        ["Kilpennathur", "Thiruvannamalai", null],
        ["Polur", "Thiruvannamalai", null],
        ["Thandramet", "Thiruvannamalai", null],
        ["Vandavasi", "Thiruvannamalai", null],
        ["Vembakkam", "Thiruvannamalai", null],
        ["Thiruvarur", "Thiruvarur", null],
        ["Kodavasal", "Thiruvarur", null],
        ["Koothanallur", "Thiruvarur", null],
        ["Mannargudi", "Thiruvarur", null],
        ["Nannilam", "Thiruvarur", null],
        ["Needamangalam", "Thiruvarur", null],
        ["Thiruthuraipoondi", "Thiruvarur", null],
        ["Valangaiman", "Thiruvarur", null],
        ["Thoothukudi", "Thoothukudi", null],
        ["Eral", "Thoothukudi", null],
        ["Ettayapuram", "Thoothukudi", null],
        ["Kayathar", "Thoothukudi", null],
        ["Kovilpatti", "Thoothukudi", null],
        ["Ottapidaram", "Thoothukudi", null],
        ["Sattankulam", "Thoothukudi", null],
        ["Srivaikundam", "Thoothukudi", null],
        ["Tiruchendur", "Thoothukudi", null],
        ["Vilathikulam", "Thoothukudi", null],
        ["Lalgudi", "Tiruchirappalli", null],
        ["Manachanallur", "Tiruchirappalli", null],
        ["Manapparai", "Tiruchirappalli", "7DGL"],
        ["Marungapuri", "Tiruchirappalli", null],
        ["Musiri", "Tiruchirappalli", null],
        ["Srirangam", "Tiruchirappalli", null],
        ["Thottiam", "Tiruchirappalli", null],
        ["Thuraiyur", "Tiruchirappalli", null],
        ["Tiruchirapalli (West)", "Tiruchirappalli", null],
        ["Tiruchirappalli (East)", "Tiruchirappalli", null],
        ["Tiruverumbur", "Tiruchirappalli", null],
        ["Tirunelveli", "Tirunelveli", null],
        ["Ambasamudram", "Tirunelveli", null],
        ["Cheranmahadevi", "Tirunelveli", null],
        ["Manur", "Tirunelveli", null],
        ["Nanguneri", "Tirunelveli", null],
        ["Palayamkottai", "Tirunelveli", null],
        ["Radhapuram", "Tirunelveli", null],
        ["Thisayanvilai", "Tirunelveli", null],
        ["Vellore", "Vellore", null],
        ["Aanikattu", "Vellore", null],
        ["Gudiyatham", "Vellore", null],
        ["K V Kuppam", "Vellore", null],
        ["Katpadi", "Vellore", null],
        ["Pernambut", "Vellore", null],
        ["Villupuram", "Villupuram", null],
        ["Gingee", "Villupuram", null],
        ["Kandachipuram", "Villupuram", null],
        ["Marakanam", "Villupuram", null],
        ["Melmalaiyanur", "Villupuram", null],
        ["Thiruvennainallur", "Villupuram", null],
        ["Tindivanam", "Villupuram", null],
        ["Vanur", "Villupuram", null],
        ["Vikravandi", "Villupuram", null],
        ["Virudhunagar", "Virudhunagar", null],
        ["Aruppukottai", "Villupuram", null],
        ["Kariyapatti", "Virudhunagar", null],
        ["Rajapalayam", "Villupuram", null],
        ["Sathur", "Virudhunagar", null],
        ["Sivakasi", "Villupuram", null],
        ["Srivilliputhur", "Virudhunagar", null],
        ["Tiruchuli", "Villupuram", null],
        ["Vembakottai", "Virudhunagar", null],
        ["Watrap", "Villupuram", null],
        ["Ariyalur", "Ariyalur", null],
        ["Andimadam", "Ariyalur", null],
        ["Sendurai", "Ariyalur", null],
        ["Udaiyarpalayam", "Ariyalur", null],
        ["Krishnagiri", "Krishnagiri", null],
        ["Anjetty", "Krishnagiri", null],
        ["Bargur", "Krishnagiri", null],
        ["Hosur", "Krishnagiri", null],
        ["Pochampalli", "Krishnagiri", null],
        ["Sulagiri", "Krishnagiri", null],
        ["Thenkanikottai", "Krishnagiri", null],
        ["Uthangarai", "Krishnagiri", null],
        ["Avinashi", "Tirupur", "5TPR"],
        ["Dharapuram", "Tirupur", "2MLR"],
        ["Kangeyam", "Tirupur", "2MLR"],
        ["Madathukkulam", "Tirupur", "3POL"],
        ["Palladam", "Tirupur", "5TPR"],
        ["Udumalaipettai", "Tirupur", "3POL"],
        ["Chengalpattu", "Chengalpattu", null],
        ["Cheyyur", "Chengalpattu", null],
        ["Maduranthakam", "Chengalpattu", null],
        ["Pallavaram", "Chengalpattu", null],
        ["Tambaram", "Chengalpattu", null],
        ["Thirukalukundram", "Chengalpattu", null],
        ["Tiruporur", "Chengalpattu", null],
        ["Vandalur", "Chengalpattu", null],
        ["Kallakurichi", "Kallakurichi", null],
        ["Chinnaselam", "Kallakurichi", null],
        ["Kalvarayan Hills", "Kallakurichi", null],
        ["Sankarapuram", "Kallakurichi", null],
        ["Tirukoilur", "Kallakurichi", null],
        ["Ulundurpet", "Kallakurichi", null],
        ["Arakkonam", "Ranipet", null],
        ["Arcot", "Ranipet", null],
        ["Kalavai", "Ranipet", null],
        ["Nemili", "Ranipet", null],
        ["Sholingur", "Ranipet", null],
        ["Walajah", "Ranipet", null],
        ["Tenkasi", "Tenkasi", null],
        ["Alangulam", "Tenkasi", null],
        ["Kadayanallur", "Tenkasi", null],
        ["Sankarankovil", "Tenkasi", null],
        ["Shenkottai", "Tenkasi", null],
        ["Sivagiri", "Tenkasi", null],
        ["Thiruvengadam", "Tenkasi", null],
        ["Tirupathur", "Tirupathur", null],
        ["Ambur", "Tirupathur", null],
        ["Natrampalli", "Tirupathur", null],
        ["Vaniyambadi", "Tirupathur", null],
        ["Mayiladuthurai", "Mayiladuthurai", null],
        ["Kuthalam", "Mayiladuthurai", null],
        ["Sirkali", "Mayiladuthurai", null],
        ["Tharangambadi", "Mayiladuthurai", null],
        ["Uthukuli", "Tirupur", "1GOB"],
        ["Coimbatore North", "Coimbatore", "4CBE"],
        ["Coimbatore South", "Coimbatore", "4CBE"],
        ["Sangagiri", "Erode", "6ERD"],
        ["Tiruppur North", "Tirupur", "5TPR"],
        ["Tiruppur South", "Tirupur", "5TPR"]
    ];

    for (let i = 0; i < taluks.length; i++) {
        console.log(taluks[i]);

        /*
        let name: string = taluks[i][0] || '';
        let district: string = taluks[i][1] || '';
        let branch: string = taluks[i][2] || '';

        if (branch) {
            await prisma.taluk.create({
                data: {
                    talukName: name,
                    branch: {
                        connect: {
                            branchCode: branch
                        }
                    },
                    district: {
                        connect: {
                            districtName: district
                        }
                    },
                },
            })
            continue;
        } else {

            await prisma.taluk.create({
                data: {
                    talukName: name,
                    district: {
                        connect: {
                            districtName: district
                        }
                    },
                },
            })
        }*/

    }

}

main()
    .then(async () => {
        await prisma.$disconnect()
    })
    .catch(async (e) => {
        console.error(e)
        await prisma.$disconnect()
        process.exit(1)
    })
